### ISSUE TITLE
Support for non-html sources

### ISSUE THREAD

**Issue by tomaszmichalak** [Knotx/knotx-fragments-chrome-extension#25]
**Is your feature request related to a problem? Please describe.**
Knot.x can expose some web API that responds with JSON. In the response JSON body Knot.x can add some debug data to display. The mechanism should be able to process such other content sources.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Voycawojka** [comment]
The current solution in the PR is to call the page URL again to retrieve the response. This is not reliable as the response can be different and so I am researching a different solution. 

Solution from the article suggested in [this comment](https://github.com/Knotx/knotx-fragments-chrome-extension/pull/117#discussion_r448883912) (intercepting the response from the server) doesn't work in our case because, quote:
> There’s no way to make this work with requests that are fired on load of the page [...]

It seems that the only way left is to read the JSON directly from the page's source code. Chromium-based browsers wrap the contents of text files so that a regular JSON becomes this in the page's source code:
```html
<html>
 <head></head>
 <body>
  <pre style="word-wrap: break-word; white-space: pre-wrap;">JSON FILE CONTENT</pre>
 </body>
</html>
```
Of course, it wouldn't be a problem to just read the JSON from this markup. The problem is that this code can be modified by other browser extensions before our extension can read it.

I'm trying to use the `MutationObserver` to get the markup before anything modifies it (solution vaguely described [here](https://stackoverflow.com/questions/50988885/chrome-extension-get-the-true-raw-html-document-before-javascript-rendering)) but I'm still not sure it will work.

### Suggested solution that will work most of the time
It looks like the browser extensions that prettify JSON don't change the `<pre>` node with JSON inside. It means that we can just ignore other browser extensions and get the JSON. Of course the con is that there is no guarantee that something else won't actually modify the markup in a way that conflicts with our app. I think this would be a rare case, though. If this happen, we can display a message suggesting to use another JSON prettifying extension that is compatible with Knot.x Chrome Extension.

### Other solutions
Other possible solutions:
- If we can get the `MutationObserver` to work then it will be the way to go
- We could also modify the backend so that in debug mode it can return the exact same response again if requested
