### ISSUE TITLE
Snapshot tests with Cypress

### ISSUE THREAD

**Issue by tomaszmichalak** [Knotx/knotx-fragments-chrome-extension#43]
**Is your feature request related to a problem? Please describe.**
We want to do some end to end tests. This task is to create some PoC that would use Cypress with Azure Pipelines.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Voycawojka** [comment]
Cannot proceed further for the time being because of unresolved problem of Cypress not detecting Chrome installed on the system on Windows.

There is a possibility to load extensions in Cypress (e.g. `cypress-browser-extension-plugin`). However, it doesn't seem to be a way of testing an extension that renders in dev tools instead of being standalone

**Comment by tomaszmichalak** [comment]
We decided to validate components with Storybook.
